plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/jamh/jhc-local/code-proj/pers-test/pwa"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]